import { motion } from "framer-motion";
import Seo from "@/components/Seo.tsx";

const TermsPage = () => (
  <>
    <Seo
      title="Terms of Service — Hold for Jesus"
      description="Terms of service for Hold for Jesus, including acceptable use, limitations, data handling, and community content responsibilities."
      path="/terms"
    />

    <div className="max-w-2xl mx-auto px-6 py-12">
      <motion.div
        className="space-y-6"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <h1 className="text-3xl font-bold text-primary font-special-elite">Terms of Service</h1>

        <div className="space-y-4 text-sm text-foreground leading-relaxed">
          <p>
            <strong>Effective date:</strong> The dawn of creation.
          </p>

          <h2 className="font-bold text-lg text-foreground mt-6">1. Acceptance</h2>
          <p>
            By using Hold for Jesus ("the Hotline"), you acknowledge that this is a
            comedy/entertainment application and not a genuine spiritual service, prayer hotline, or
            substitute for professional counseling.
          </p>

          <h2 className="font-bold text-lg text-foreground mt-6">2. No Divine Guarantees</h2>
          <p>
            Responses are generated by artificial intelligence and do not constitute spiritual
            advice, religious counsel, or divine communication. No miracles are guaranteed. Void
            where prohibited by the laws of physics.
          </p>

          <h2 className="font-bold text-lg text-foreground mt-6">3. Respectful Use</h2>
          <p>
            While the app is satirical, we expect users to engage respectfully. Don't use the
            hotline to generate harmful, hateful, or abusive content targeting any religious
            tradition or group.
          </p>

          <h2 className="font-bold text-lg text-foreground mt-6">4. Crisis Situations</h2>
          <p>
            This app is not equipped to handle real emergencies. If you are in crisis, please
            contact the 988 Suicide & Crisis Lifeline (call or text 988) or visit our crisis
            resources page.
          </p>

          <h2 className="font-bold text-lg text-foreground mt-6">5. Limitation of Liability</h2>
          <p>
            The Hotline is provided "as is" without warranties of any kind, divine or otherwise. We
            are not responsible for any spiritual, emotional, or existential outcomes resulting from
            use of this service.
          </p>

          <h2 className="font-bold text-lg text-foreground mt-6">6. Intellectual Property</h2>
          <p>
            The Satan-Proof Sole™ is a trademark of the Celestial Bureaucracy (not really). All
            content is for entertainment purposes.
          </p>

          <h2 className="font-bold text-lg text-foreground mt-6">7. Data & Privacy</h2>
          <p>
            The service is anonymous by default (no account required), but it does process and store
            limited operational metadata for reliability and safety. If you choose to post to
            community features (such as the Prayer Wall), that submitted content may be stored
            server-side according to product behavior and retention rules.
          </p>

          <h2 className="font-bold text-lg text-foreground mt-6">8. User Content</h2>
          <p>
            You are responsible for content you submit. By submitting community content, you grant
            us a non-exclusive license to display and process it within the app for operation,
            moderation, and safety enforcement.
          </p>
        </div>
      </motion.div>
    </div>
  </>
);

export default TermsPage;
