import { motion } from "framer-motion";
import {
  AlertTriangle,
  BookOpen,
  Cpu,
  Database,
  Eye,
  Heart,
  Layers,
  Lock,
  Shield,
  Zap,
} from "lucide-react";
import { Link } from "react-router-dom";
import Seo from "@/components/Seo.tsx";

const Section = ({
  icon,
  title,
  children,
}: {
  icon: React.ReactNode;
  title: string;
  children: React.ReactNode;
}) => (
  <motion.div
    className="bg-card border border-border rounded-lg p-6 space-y-3"
    initial={{ opacity: 0, y: 12 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true }}
    transition={{ duration: 0.4 }}
  >
    <div className="flex items-center gap-2">
      {icon}
      <h2 className="font-bold text-foreground font-special-elite">{title}</h2>
    </div>
    <div className="text-sm text-muted-foreground leading-relaxed space-y-2">{children}</div>
  </motion.div>
);

const CodeBlock = ({ children }: { children: React.ReactNode }) => (
  <pre className="bg-muted/50 rounded-md p-4 text-[10px] font-mono text-muted-foreground overflow-x-auto leading-relaxed whitespace-pre">
    {children}
  </pre>
);

const TransparencyPage = () => (
  <>
    <Seo
      title="How It Works — Hold for Jesus"
      description="Architecture, moderation, AI workflow, data pipelines, and privacy: everything about how Hold for Jesus works under the hood."
      path="/transparency"
    />

    <div className="max-w-2xl mx-auto px-6 py-12">
      <motion.div
        className="space-y-8"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="text-center space-y-3">
          <h1 className="text-3xl font-bold text-primary font-special-elite">How It Works</h1>
          <p className="text-sm text-muted-foreground max-w-md mx-auto">
            Architecture, safety, data pipelines, and privacy — the full picture.
          </p>
        </div>

        {/* ═══ What it is ═══ */}
        <Section icon={<Eye className="h-4 w-4 text-primary" />} title="What This Is">
          <p>
            <strong>Hold for Jesus</strong> is a satirical AI prayer hotline that imagines what it
            would be like if the divine ran a customer service department. The humor targets
            corporate call center culture — never the beliefs themselves.
          </p>
          <p>
            Six faith traditions each get a unique voice, hotline number, AI persona, departments,
            and closing prayer style. Responses are generated by AI and should not be taken as
            spiritual counsel, therapy, or divine communication.
          </p>
        </Section>

        {/* ═══ What it isn't ═══ */}
        <Section
          icon={<AlertTriangle className="h-4 w-4 text-destructive" />}
          title="What This Is Not"
        >
          <ul className="list-disc list-inside space-y-1">
            <li>
              Not a real prayer service — responses are generated by software, not clergy or deities
            </li>
            <li>Not therapy or counselling — the AI is a comedy character</li>
            <li>Not affiliated with any religion, denomination, or deity</li>
            <li>Not a replacement for human spiritual guidance</li>
          </ul>
          <p className="text-xs text-muted-foreground/70 italic pt-1">
            The satirical framing is itself a safety guardrail: by presenting responses as "divine
            customer service," we make it impossible to mistake them for actual spiritual authority.
          </p>
        </Section>

        {/* ═══ The Split Brain ═══ */}
        <Section icon={<Heart className="h-4 w-4 text-primary" />} title="The Split Brain">
          <p>
            The site is built on a deliberate tonal duality: <strong>satirical comedy</strong> and{" "}
            <strong>sincere data/resources</strong> coexist in the same application, and both halves
            make the other stronger.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
            <div className="bg-muted/50 rounded-md p-3">
              <p className="text-xs font-semibold text-foreground mb-1">🎭 The Hotline</p>
              <p className="text-[11px] text-muted-foreground">
                Satirical prayer processing. Warm corporate-divine comedy. The joke.
              </p>
              <p className="text-[10px] text-muted-foreground/60 mt-1">
                Hotline · History · Community
              </p>
            </div>
            <div className="bg-muted/50 rounded-md p-3">
              <p className="text-xs font-semibold text-foreground mb-1">🌍 The Real World</p>
              <p className="text-[11px] text-muted-foreground">
                Pain Index, AI Incidents, Crisis Help. No satire — real data, real help. The point.
              </p>
              <p className="text-[10px] text-muted-foreground/60 mt-1">
                Crisis · Pain Index · AI Incidents
              </p>
            </div>
          </div>
          <p className="text-xs text-muted-foreground/70 italic pt-1">
            The Community page sits between the two — a sincere anonymous space where users can
            share reflections, light candles, and add voices to global causes.
          </p>
        </Section>

        {/* ═══ Six Faiths ═══ */}
        <Section icon={<BookOpen className="h-4 w-4 text-primary" />} title="Six Faith Traditions">
          <p>
            Each tradition gets a unique AI persona, voice inspiration, departments, and branded
            hotline:
          </p>
          <div className="space-y-2 pt-1">
            {[
              {
                emoji: "✝️",
                name: "Hold for Jesus",
                voice: "C.S. Lewis — warm, literary, witty",
                mgr: "Jesus (Employee of the Millennium)",
              },
              {
                emoji: "☪️",
                name: "Hold for Allah",
                voice: "Rumi — poetic mysticism + mercy",
                mgr: "Jibril (Head of Angelic Communications)",
              },
              {
                emoji: "✡️",
                name: "Hold for Hashem",
                voice: "Jewish grandmother + Talmudic wit",
                mgr: "Moses (Senior VP of Exodus Operations)",
              },
              {
                emoji: "🕉️",
                name: "Hold for Brahman",
                voice: "Bhagavad Gita teacher + cosmic warmth",
                mgr: "Ganesha (Chief Obstacle Removal Officer)",
              },
              {
                emoji: "☸️",
                name: "Hold for Enlightenment",
                voice: "Thich Nhat Hanh — gentle, present",
                mgr: "Avalokiteshvara (Head of Compassion)",
              },
              {
                emoji: "🔬",
                name: "Hold for Reason",
                voice: "Carl Sagan — cosmic wonder + humanism",
                mgr: "Carl Sagan's Ghost (Pale Blue Dot Division)",
              },
            ].map((f) => (
              <div
                key={f.name}
                className="flex items-start gap-2.5 bg-muted/30 rounded-md px-3 py-2"
              >
                <span className="text-sm">{f.emoji}</span>
                <div className="min-w-0">
                  <p className="text-xs font-semibold text-foreground">{f.name}</p>
                  <p className="text-[10px] text-muted-foreground">{f.voice}</p>
                  <p className="text-[10px] text-muted-foreground/60">{f.mgr}</p>
                </div>
              </div>
            ))}
          </div>
          <p className="text-[11px] text-muted-foreground pt-1">
            Each tradition also has 3–4 themed departments (e.g., Old Testament Complaints, Sufi
            Poetry Desk, Karma Accounting, Zen Koans Desk) and four optional prayer categories:
            Gratitude, Guidance, Complaint, Emergency.
          </p>
        </Section>

        {/* ═══ AI Workflow ═══ */}
        <Section icon={<Cpu className="h-4 w-4 text-primary" />} title="AI Workflow Architecture">
          <p>
            The prayer system uses a{" "}
            <strong>single edge function with a 6-section modular architecture</strong>. Content
            (prompt templates) and logic (composition) are strictly separated:
          </p>
          <CodeBlock>{`┌─────────────────────────────────────────────┐
│ 1. Rate Limiting                            │
│    IP-based sliding window (10 req/min)     │
├─────────────────────────────────────────────┤
│ 2. Detection Patterns                       │
│    Regex catalog: crisis > troll >          │
│    off_topic > reality_anchor > scrupulosity│
├─────────────────────────────────────────────┤
│ 3. Message Classifier                       │
│    Pure function → mode + detectedSignals[] │
├─────────────────────────────────────────────┤
│ 4. Prompt Registry                          │
│    ALL prompt text: personas, departments,  │
│    categories, safety overrides             │
├─────────────────────────────────────────────┤
│ 5. PromptBuilder                            │
│    Composable builder — ALL logic, no text  │
│    base() → section() → when() → build()   │
├─────────────────────────────────────────────┤
│ 6. Request Handler                          │
│    Validate → Classify → AI Call → Post-    │
│    process → Closing Prayer → Log → Respond │
└─────────────────────────────────────────────┘`}</CodeBlock>
          <p className="text-[11px] text-muted-foreground">
            <strong>Prompt composition:</strong> Faith persona + core rules + department sub-prompt
            + category prompt + safety override — all layered from a declarative registry. A
            Christianity + Saints Desk + Guidance + Scrupulosity request produces a completely
            different prompt than Islam + Sufi + Complaint + Normal.
          </p>
          <p className="text-[11px] text-muted-foreground">
            <strong>Dual AI calls:</strong> Each request triggers up to two parallel calls — the
            main response and a faith-appropriate closing prayer. Closing prayers are skipped for
            crisis, troll, and off-topic modes.
          </p>
        </Section>

        {/* ═══ Safety & Moderation ═══ */}
        <Section icon={<Shield className="h-4 w-4 text-primary" />} title="Safety & Moderation">
          <p>
            Every message passes through a <strong>hybrid two-layer detection system</strong> —
            instant regex patterns followed by AI self-classification:
          </p>
          <div className="bg-muted/50 rounded-md p-4 space-y-2 text-xs">
            <p>
              <strong>Crisis detection (Priority 1)</strong> — Messages expressing self-harm or
              suicidal ideation are intercepted immediately. All satire drops. The AI responds with
              genuine compassion, the <strong>988 Suicide & Crisis Lifeline</strong>, and the Crisis
              Text Line.
            </p>
            <p>
              <strong>Troll absorption (Priority 2)</strong> — Abusive messages are "routed" to a
              fictional department (Celestial Noise Desk, Divine Spam Filter). No scolding — just
              quiet, in-character redirection.
            </p>
            <p>
              <strong>Off-topic redirect (Priority 3)</strong> — Non-prayer requests get a warm,
              funny redirect to earthly services.
            </p>
            <p>
              <strong>Reality anchor (Priority 4)</strong> — If someone treats the AI as literally
              divine, it breaks the fourth wall: "I'm an AI comedy app, not God."
            </p>
            <p>
              <strong>Scrupulosity care (Priority 5)</strong> — Messages showing signs of religious
              OCD receive extra-gentle, reassurance-first responses.
            </p>
          </div>
          <p className="text-[11px] text-muted-foreground">
            <strong>Layer 2 — AI Self-Classification:</strong> Normal-mode prompts include a [TROLL]
            self-classify instruction. If the AI detects subtle bad-faith intent that regex missed,
            it prefixes its response — caught and reclassified in the same API call with zero added
            latency.
          </p>
          <p className="text-xs text-muted-foreground/70">
            Safety logging stores mode, detected signals, and applied guardrails in{" "}
            <code className="text-[10px] bg-muted px-1 rounded">safety_signals</code>. This pipeline
            is metadata-focused and does not persist full prayer body text as part of safety
            analytics.
          </p>
        </Section>

        {/* ═══ Data Pipeline ═══ */}
        <Section
          icon={<Database className="h-4 w-4 text-primary" />}
          title="Data Pipeline — Global Pain Index"
        >
          <p>
            A serverless ETL pipeline ingests data through{" "}
            <strong>13 adapters across 10 source systems</strong>, normalizes it through a
            registry-driven scoring model, and produces the composite Pain Index:
          </p>
          <CodeBlock>{`Source Adapters (13 active)
    ↓
raw_records (immutable audit trail)
    ↓
canonical_entities (normalized schema)
    ↓
normalization_registry (weights + baselines)
    ↓
derived_scores (composite index)
    ↓
suffering_index (cached final score)`}</CodeBlock>

          <p className="text-[11px] text-muted-foreground">
            <strong>Sources:</strong>
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-1 text-[10px] text-muted-foreground pt-1">
            {[
              ["World Bank", "4 indicators", "Authoritative"],
              ["UNHCR", "Displacement", "Authoritative"],
              ["Global Slavery Index", "Modern slavery", "Authoritative"],
              ["GDELT", "Conflict events", "Signal Only"],
              ["UN SDG 16.1.1", "Homicide rate", "Authoritative"],
              ["ACLED", "Armed conflict", "Authoritative"],
              ["WHO", "Neonatal mortality", "Authoritative"],
              ["USGS", "Earthquakes", "Authoritative"],
              ["NASA FIRMS", "Active fires", "Authoritative"],
              ["UN OCHA/HDX", "Humanitarian data", "Authoritative"],
            ].map(([source, desc, badge]) => (
              <div key={source} className="flex items-baseline gap-1.5">
                <span className="font-medium text-foreground">{source}</span>
                <span className="text-muted-foreground/60">— {desc}</span>
                <span
                  className={`text-[8px] px-1 py-0.5 rounded font-medium ${
                    badge === "Signal Only"
                      ? "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300"
                      : ""
                  }`}
                  style={
                    badge !== "Signal Only"
                      ? {
                          backgroundColor: "hsl(var(--badge-authoritative) / 0.15)",
                          color: "hsl(var(--badge-authoritative-fg))",
                        }
                      : undefined
                  }
                >
                  {badge}
                </span>
              </div>
            ))}
          </div>

          <p className="text-[11px] text-muted-foreground pt-2">
            <strong>Normalization:</strong> Each indicator has baseline min/max, direction
            (higher-is-worse or lower-is-worse), and weight — all stored in a database registry
            rather than hardcoded. Raw values are min-max normalized to 0–1, direction-inverted
            where needed, then weighted into a composite 0–100 score.
          </p>
          <p className="text-[11px] text-muted-foreground">
            <strong>Refresh:</strong> A scheduled job triggers the pipeline every 6 hours.
          </p>
        </Section>

        {/* ═══ AI Incident Pipeline ═══ */}
        <Section icon={<Layers className="h-4 w-4 text-primary" />} title="AI Incident Pipeline">
          <p>
            The{" "}
            <Link to="/incidents" className="text-primary hover:underline font-medium">
              AI Incident Archive
            </Link>{" "}
            ingests data from the{" "}
            <a
              href="https://incidentdatabase.ai"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              AI Incident Database
            </a>{" "}
            (AIID) through a dedicated adapter following the same pipeline pattern:
          </p>
          <CodeBlock>{`AIID GraphQL API
    ↓
raw_records (immutable)
    ↓
canonical_entities (ai_harm_observation)
    ↓
derived vulnerability classification
    ↓
ai_incident_summary (cached widget data)`}</CodeBlock>
          <p className="text-[11px] text-muted-foreground">
            <strong>Classification:</strong> A 12-category keyword taxonomy maps incidents to
            vulnerable populations (children, minorities, patients, etc.). Each incident also
            receives a <strong>harm domain</strong> (algorithmic bias, surveillance, automation
            error) and <strong>severity signal</strong> (high/medium/low). Classifications are
            labeled as{" "}
            <span
              className="inline-block text-[9px] font-medium px-1 py-0.5 rounded"
              style={{
                backgroundColor: "hsl(var(--badge-derived) / 0.15)",
                color: "hsl(var(--badge-derived-fg))",
              }}
            >
              Derived
            </span>{" "}
            — our inference, not AIID's taxonomy.
          </p>
          <p className="text-[11px] text-muted-foreground">
            <strong>Safeguards:</strong> SHA256 idempotency, max 3 categories per incident, 5,000
            incident fetch guard, exponential backoff retries, and trend analysis (12-month window).
          </p>
        </Section>

        {/* ═══ Privacy ═══ */}
        <Section icon={<Lock className="h-4 w-4 text-primary" />} title="Privacy Architecture">
          <ul className="list-disc list-inside space-y-1">
            <li>No accounts required — the entire app works anonymously</li>
            <li>
              Hotline flows store operational/safety metadata; local history/favorites stay in
              browser storage
            </li>
            <li>Prayer Wall submissions are stored server-side when users explicitly post them</li>
            <li>
              History and favorites are stored locally on your device only (Zustand + localStorage)
            </li>
            <li>Safety logs record interaction mode and metadata for abuse/care controls</li>
            <li>The Crisis Resources page has zero analytics — no tracking of any kind</li>
            <li>Global activity indicators use only broad city/region labels</li>
            <li>Prayer Wall entries are designed to be ephemeral</li>
          </ul>
        </Section>

        {/* ═══ Tech Stack ═══ */}
        <Section icon={<Zap className="h-4 w-4 text-primary" />} title="Tech Stack">
          <div className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-1.5 text-[11px]">
            {[
              ["Frontend", "React 18 + TypeScript + Vite"],
              ["Styling", "Tailwind CSS + shadcn/ui + CSS design tokens (HSL)"],
              ["Animation", "Framer Motion"],
              ["State", "Zustand (local persistence)"],
              ["Audio", "Web Audio API (procedural hold music, typewriter sounds)"],
              ["Backend", "Supabase Edge Functions (Deno)"],
              ["AI", "Google Gemini 3 Flash"],
              ["Database", "PostgreSQL"],
              ["Scheduling", "pg_cron + pg_net (6-hour data refresh)"],
              ["Error Handling", "Global Error Boundary with themed fallback"],
              ["SEO", "react-helmet-async, semantic HTML, JSON-LD ready"],
            ].map(([layer, tech]) => (
              <div key={layer} className="contents">
                <span className="font-semibold text-foreground">{layer}</span>
                <span className="text-muted-foreground">{tech}</span>
              </div>
            ))}
          </div>
        </Section>

        <p className="text-xs text-muted-foreground italic text-center">
          Built with love, irreverence, and zero divine endorsement.
        </p>
      </motion.div>
    </div>
  </>
);

export default TransparencyPage;
