CREATE TABLE IF NOT EXISTS public.request_rate_limits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope text NOT NULL,
  identifier_hash text NOT NULL,
  window_started_at timestamptz NOT NULL,
  request_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (scope, identifier_hash, window_started_at)
);

CREATE INDEX IF NOT EXISTS idx_request_rate_limits_window_started_at
  ON public.request_rate_limits (window_started_at);

ALTER TABLE public.request_rate_limits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "No public reads on request_rate_limits" ON public.request_rate_limits;
CREATE POLICY "No public reads on request_rate_limits"
  ON public.request_rate_limits
  FOR SELECT TO anon, authenticated
  USING (false);

DROP POLICY IF EXISTS "No public writes on request_rate_limits" ON public.request_rate_limits;
CREATE POLICY "No public writes on request_rate_limits"
  ON public.request_rate_limits
  FOR ALL TO anon, authenticated
  USING (false)
  WITH CHECK (false);

CREATE OR REPLACE FUNCTION public.enforce_rate_limit(
  p_scope text,
  p_identifier text,
  p_window_seconds integer,
  p_max_requests integer
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_bucket timestamptz;
  expires_at timestamptz;
  retry_after_seconds integer;
  current_count integer;
  hashed_identifier text;
BEGIN
  current_bucket := to_timestamp(
    floor(extract(epoch FROM now()) / GREATEST(p_window_seconds, 1)) * GREATEST(p_window_seconds, 1)
  );
  hashed_identifier := md5(COALESCE(p_identifier, 'unknown'));

  INSERT INTO public.request_rate_limits (scope, identifier_hash, window_started_at, request_count, updated_at)
  VALUES (p_scope, hashed_identifier, current_bucket, 1, now())
  ON CONFLICT (scope, identifier_hash, window_started_at)
  DO UPDATE SET
    request_count = public.request_rate_limits.request_count + 1,
    updated_at = now()
  RETURNING request_count INTO current_count;

  DELETE FROM public.request_rate_limits
  WHERE window_started_at < now() - make_interval(secs => GREATEST(p_window_seconds * 10, 600));

  expires_at := current_bucket + make_interval(secs => GREATEST(p_window_seconds, 1));
  retry_after_seconds := GREATEST(1, CEIL(EXTRACT(epoch FROM (expires_at - now())))::integer);

  RETURN jsonb_build_object(
    'allowed', current_count <= p_max_requests,
    'request_count', current_count,
    'retry_after_seconds', retry_after_seconds
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.enforce_rate_limit(text, text, integer, integer) TO service_role;