// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
export const isReactSnap =
  typeof navigator !== "undefined" && navigator.userAgent.includes("ReactSnap");

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
export const missingSupabaseEnvMessage =
  "Missing Supabase env vars. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in Vercel Project Settings > Environment Variables.";

const resolvedSupabaseUrl = SUPABASE_URL || "https://example.supabase.co";
const resolvedSupabasePublishableKey = SUPABASE_PUBLISHABLE_KEY || "public-anon-key";

if (!isSupabaseConfigured && !isReactSnap) {
  console.error(missingSupabaseEnvMessage);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  resolvedSupabaseUrl,
  resolvedSupabasePublishableKey,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
